### ISSUE TITLE
Use relative image paths to fix broken layout on sites which run redmin on a sub-URI

### ISSUE THREAD

**Issue by flipsa** [Smile-SA/redmine_smile_togglesidebar#2]
Problem:
Our redmine installation is on https://example.com/redmine and not its own (sub)domain. Your plugin works fine, but the images for the show/hide button aren't loaded. 

Fix: 
You used relative paths in "lib/helpers/smile_helpers_application.rb" on line 91 and 92 for the image locations. Dropping the leading slash from the image location paths fixes the problem for me, and I guess it should work on any redmine installation.

I'd submit a PR, but the changes are so trivial that I didn't bother ;)

Thanks for the plugin!

**Comment by Utopism** [comment]
Hi, sorry for my so late reply.

Removing the leading slash does not work at all for me.

The problem is that there is no standard solution to have a relative root :

This can be done with :
RedmineApp::Application.routes.default_scope
OR
Redmine::Utils::relative_url_root = "/redmine"
OR
other method I haven't seen.

So there is no single method to get the relative root value.

**Comment by Utopism** [comment]
Hi,
As there is a **Redmine preferred** solution stated, I am going to use it to detect a **relative root** :
http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI#Using-RedmineUtils-preferred-solution

**Comment by Utopism** [comment]
Fixed, see V1.0.6
